version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: car
    volumes:
      - db-data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:9.16.1
    depends_on:
      - db
    volumes:
      - ./sql:/flyway/sql
    command: -url=jdbc:postgresql://db:5432/car -user=postgres -password=1234 migrate

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/car
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    volumes:
      - ./logs:/app/logs

volumes:
  db-data:
